import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const Home: NextPage = () => {
    const { user, isSignedIn, isLoaded } = useUser();
    const router = useRouter();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-full flex flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white overflow-y-scroll">
                {isSignedIn && user &&
                    <div>
                        <p>Succeccfully logged in!</p>
                        <Link href={`./${user.id}`}>
                            <h1 className="underline">Continue to Application</h1>
                        </Link>
                    </div>
                }
                {
                    !isSignedIn &&
                    <SignInButton />
                }
            </main>
        </>
    );
};

export default Home;
